# Generated by Django 2.2.14 on 2020-10-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptepayant',
            name='photoprofil',
        ),
    ]
