# Generated by Django 2.2.14 on 2020-08-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCompteGratuit',
        ),
    ]
