# Generated by Django 2.2.14 on 2020-07-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nomutilisateur',
        ),
    ]
