# Generated by Django 2.2.14 on 2020-10-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_comptepayant_photoprofil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptegratuit',
            old_name='photocouverture',
            new_name='photoprofil',
        ),
    ]
