# Generated by Django 2.2.14 on 2020-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_delete_profilecomptegratuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptegratuit',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
