# Generated by Django 2.2.14 on 2020-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200823_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptegratuit',
            name='photocouverture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='comptegratuit',
            name='photoprofil',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
