# Generated by Django 2.2.14 on 2020-07-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200726_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_join',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
