# Generated by Django 2.2.14 on 2020-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_comptegratuit_photoprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptepayant',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
