# Generated by Django 2.2.14 on 2020-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200827_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptegratuit',
            name='photocouverture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='comptegratuit',
            name='photoprofil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
