# Generated by Django 2.2.14 on 2020-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200726_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptegratuit',
            name='photocouverture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='comptegratuit',
            name='photoprofil',
            field=models.FileField(upload_to=''),
        ),
    ]
