# Generated by Django 2.2.14 on 2020-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20200726_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptegratuit',
            name='photocouverture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comptegratuit',
            name='photoprofil',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
