# Generated by Django 2.2.14 on 2020-08-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20200801_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_join',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
