# Generated by Django 2.2.14 on 2020-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20200805_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptegratuit',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='comptegratuit',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='comptepayant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='comptepayant',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_join',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
