# Generated by Django 2.2.14 on 2020-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200827_0803'),
        ('Restaurant', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts', to='Accounts.Comptegratuit'),
        ),
    ]
