# Generated by Django 2.2.14 on 2020-10-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20201002_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='totallikes',
        ),
    ]
