# Generated by Django 2.2.14 on 2020-10-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_remove_commentaire_totallikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturepost',
            name='intitule',
        ),
        migrations.RemoveField(
            model_name='picturerestau',
            name='intitule',
        ),
    ]
