# Generated by Django 2.2.14 on 2020-10-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_auto_20201002_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='restau_pics/defaultrestau.png', null=True, upload_to='restau_pics'),
        ),
        migrations.DeleteModel(
            name='PicturePost',
        ),
    ]
