# Generated by Django 2.2.14 on 2020-10-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_auto_20201002_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='picture_default',
            field=models.ImageField(default='restau_pics/defaultrestau.png', upload_to='restau_pics'),
        ),
    ]
