# Generated by Django 2.2.14 on 2020-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_restaurant_picture_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
