# Generated by Django 2.2.14 on 2020-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_commentaire_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_votes',
            field=models.IntegerField(default=0, verbose_name='Total votes'),
        ),
    ]
