# Generated by Django 2.2.14 on 2020-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaucommentaire'),
        ),
    ]
