# Generated by Django 2.2.14 on 2020-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_auto_20201003_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_comme',
            field=models.IntegerField(default=0, verbose_name='Total commentaires'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='percentage'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_rating',
            field=models.IntegerField(default=0, verbose_name='Total Rating'),
        ),
    ]
