# Generated by Django 2.2.14 on 2020-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200827_0803'),
        ('Restaurant', '0009_commentaire_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.ManyToManyField(related_name='commentairelike', to='Accounts.Comptegratuit'),
        ),
    ]
