# Generated by Django 2.2.14 on 2020-10-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_auto_20201003_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='total_rating',
        ),
    ]
