# Generated by Django 2.2.14 on 2020-10-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_remove_restaurant_total_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='total_comme',
        ),
    ]
