# Generated by Django 2.2.14 on 2020-10-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_remove_restaurant_total_comme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='totallikes',
        ),
    ]
