# Generated by Django 2.2.14 on 2020-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_remove_post_totallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totallikes',
            field=models.IntegerField(default=0, verbose_name='total'),
        ),
    ]
