# Generated by Django 2.2.14 on 2020-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0014_post_totallikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='adresse',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='intitule',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, choices=[('cheap eats', 'cheap eats'), ('mide Rang', 'mide Rang'), ('Fine Dining', 'Fine Dining')], max_length=50, null=True),
        ),
    ]
