# Generated by Django 2.2.14 on 2020-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0017_auto_20201005_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
